const fs = require('fs');

// Load the data generated by license-report
const rawData = JSON.parse(fs.readFileSync('license-data.json', 'utf-8'));

// Initialize an empty array for the formatted data
const formattedData = [];

// Process each library in the rawData
rawData.forEach(lib => {
    const formattedLib = {
        License: lib.licenseType,
        LibraryName: lib.name,
        LibraryLink: lib.link,  // Assuming license-report provides the library URL in the "link" field
        LicenseLink: ''  // license-report may not provide a direct link to the license file
    };
    formattedData.push(formattedLib);
});

// Save the formatted data to a new file
fs.writeFileSync('formatted-license-data.json', JSON.stringify(formattedData, null, 2));
